# Generated by Django 4.2.1 on 2023-09-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
