# Generated by Django 4.2.1 on 2023-09-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_paul_delete_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paul',
            new_name='Person',
        ),
    ]
